### ISSUE TITLE
Support for sf-cli

### ISSUE THREAD

**Issue by joernflath** [hardisgroupcom/vscode-sfdx-hardis#104]
Hello,

big fan of your VS Code Extension! Helped my Admins a lot.

Will there be support for the unified sf-cli in the future?

Kind regards
Jörn

**Comment by nvuillam** [comment]
Hi @joernflath :)

Many thanks for your feedback !

For the moment, few people are using sf CLI, but that will change because they are about to release a sf cli v2... that will accept sfdx commands !

More info: https://github.com/forcedotcom/cli/issues/2132 (cc @mshanemc )

Once it won't be in beta anymore, we'll switch the dependency to sf instead of sfdx, but keep calling sfdx commands ;)

Anyway, sfdx-hardis commands will always work, even if the commands behind are migrated from sfdx to sf, you don't need to worry about it :)
